sudo: required
services:
  - docker
language: c
cache: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath # needed on ubuntu 14.04.5 LTS / trusty
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage-deploy
  - chmod +x dommage dommage-deploy
  - export PATH=$PATH:$PWD/

script:
  - make configure build
  - dommage-deploy

env:
  matrix:
    - FLAGS="-t unix -vv --net socket"
    - FLAGS="-t unix -vv --net direct"
    - FLAGS="-t xen  -vv --net direct --dhcp false
        --ipv4 46.43.42.142/28 --ipv4-gateway 46.43.42.129"
      DEPLOY=1 XENIMG="tutorialopenmirageorg" MIRDIR="src"

  global:
  - OCAMLRUNPARAM=b
  - DOMMAGE_DEBUG=true
  - secure: QbNUGpL63lqNm1lLmVgDDq3OmT7ZuZc3ufHt5qaR00obirBsAWkpwtg5rIrG6juNDFERwqosWX2S5IeBr7X5sYJv1b4DVKufh5cOvv7b/veNtXcDGZU0IlBQLMJCZGYd2+dCrwDaBMjPyV71vlHPkmJx9NZTweZ7ISqCzcGaYLg=
  - secure: GQ5LdxZSwHjNJTMoCfvDZJ08lQrL+hGKaLpibkqMxvhUtQR10hVweFM60w8/0PQXY01dVp/ljKjnT9U2bw+INI1owwsCbQZu7hdImun40sQLxcHbnRAHVH0ltfV623RHczS91pLEH8Jv7yRLgydRo3jiS70DoNHSohaar86nOjo=
  - secure: dIoWlY0c6a8KBQkUicz3QFErvUsi38JFirMcz0zmIxbhxviWy2N3XAADgMJRedPRTgn4Z7zwXqurKyTngeZ0NWvT7qex+Ap9rBSz5hUeFdjPS0c6hemlnzB0ld+KRXws9X9z67e0r/SS2l9UZZCxN0aBSCyR9SeQ7UgHClYChYo=
  - secure: oW89y5t6QKeoED09unm0gxYp4FRIT6pDKHxwplhWTBvRcbf8pa7SBY/KjDqAPYLu4sRAJBQeCt+zEIAHMDtKd3EllGHzGf9J6izFDdVWZ+wmi8VMm35lK4UX/ZaLBMIo9fu6XMchSI3JM7ClLqAdnH5ghLlQzbWHdRVvtzKs+uo=
  - secure: dRpj6Eyzq4cFkj/9kLQXH+4gO28QAHDiW4M9ioxnO7z6CQSXrxxJqeoK6eb25tRkKcjMZ2H9JspcqjpQvJ3z3Mj89IgSLcsWgV5GPg41r5CcGL1q3jsjTiHMNoep1lImQMLZ7cOONoj/Mqa9O4BX8g8VxSDuO7O2uqc2yzvUGxo=
  - secure: CrMldjelBL+wrEtZYOF83FmHQPgQpYf1vvEp+PywvwAsY/xxEYrCHeVTuAkvYgF16n5gYsaZ0YflnEobh7vqYAx41XJvW+7EsBDwBQv77qEEgNRFmTazTN5hFRmXO684WzgI/a1lVfbgT8mBm1AxmaBa5xuLDwaL+AuvTs0Icww=
  - secure: XzzF8fOZewDmF0HCjhShOz2myJWr0TayYySiSgGyLd8jZh7wxiBsD4SpMFfiXXUEEHim+nerhAEGQdfuDXaoIGnklam9MIA6OTexVMNmr+4athx6u7dEraghELDK0nmWQ6f5UNo/H5g+lSeawM9etYxclmtDMdaLmed7jrxd/Bc=
  - secure: nqZAi6zafOzC5CUCBryWcLl2KgdT/YOUzAtagKdi7jyJwwCFnFLn2Ob6BaEkk7nQsByw/tsdX7Hxhhm21ccCrpD3Vdmx6WzkyO+l6VDE0KgiFjsTsS8pWGWYHOVpUw6HNbBJc117BiK9jDWsQcCM7YpmGlXu7tCGl1H3/gHXKOA=
  - secure: b8+kDloR4FtxtNCtb/QFuLiMI/9oq8pkA3GRRky6d+5by4EUSjksbJPwcvryrYyXFLAXpWGW3qvODURm8+lkyRN26Uv3Jk3BkykrR8vE4TCHyFnq5PffGIb3vo2Vwp0wDhbYsrU6+hdlC4hvSMMtK8Cvc47pY6EulNQKG/8h4X4=
  - secure: QHJY3lAKxcEDXwtvHOOyMwIe2Nl9oBRxV8rW/VVWTsP0q/jQyEyPXW/Qbm08KHdXKqgE2dBOvXOyoedgytfZ79F1tfqxg3bYUAGbFWEhG6e8g0xUBV1beA57byDeSP2qYmqmzHFfKVpGnjLi66piXULgcgTvrgf07cQ1aQV8RAY=
  - secure: NW6ab1zxmE/X+f//KtAqfqY11qGB2WB6gAJq9JIuwbNhn102Jj8wG0/YXj+0oVoISqRmjSldG6XZ8bquSxz2G8hQjPk/SzpJqEDWEQVTamLLrhfjv34ZxbdRO+0HpROcx8C0hYWW9VUbDuaF+jgHYLhHpjb/BIUEBsEDs35WLL4=
  - secure: aT+VsiAmuO8OKvIShU2lb/hAVSFG5Zi/Ot8Kr/GsTC8z1lpncEF5aigo2kIktG176ul50zsaELxjCwjSAQugRselIstUnwkU4giHQjj5tM+vtSB6qO7syuEUvXULTRA4V0r9fWUUTLaWBwDVL2UTDXl5WzCch5HtbbIWWs440XE=
  - secure: fcz6pFfC1wRhdAkXUY9sB9AwG0Yzi8FjLZuOzEuzqqEdP7Lcyh9rM6zdxeTX9W87kljaw7UtFdccV29bNDm5Vb60MZZkz7GJeQZ1QwLNxzsvgTDygUNfRnAS0DubS6tplfvXp8x0xsUoCWwmxWBZ+GxYrYJIOIXHvz4P2fR3q6k=
  - secure: QSg6bozlpLYjy6lw9GvKYWesymMxGg8pg9t46VyI1SvBTimGGo8Nl/8Jo76WKux9KfWm0W7t8LJSFRMNowj1NRTT7bCHU7Zkn3XyKUeCgfcNcwbWrr0AQ3iiQCSDb1byJK7fVXjE831CwF0PNxZTU8c0sZ9/UczodfO3CyOkBRw=
  - secure: sqm8jmoVFGrUti+/g4MLeorFXqxKiZP6AnD2kQtfQMCv0SqkA00UyhS+0IvAcZ0lJ3LtQaA+yYqSSg93BbYWNYSxI+R9LcB+knjU6weYoznsLRgDL0cgumh8sqne70dHS532gbbvorHg0efQy+5C5Tn4TvhoncfGse+KmH0Psxo=
  - secure: rKGVhs6Z46I+Flr5rngWx521VE6YvB9yKNBf46hZRIHO7a52oujgasDyD+L9zLHHpHH9vbE7zXDV4A9kesuzM7R/KpCNsLjcOEP3Hzfs+Wd5DsF5uLxNPwN3NUbCwuTe+sug8ovF4cGGEjjpBRxTRO0L1b+dKewksCipuu/Ba9E=
  - secure: H9vdBYPtpua25uoGLLhIVrRK4+wHFHtjOh30NxmPZMsMBUKi/Oa1/hmD/oCzYlBNEDwpry6UCUI7+zzJz04yzYj/HaV262jHSnFJahVr6Nk3K5PkpZnAqVMKHlfREXcLzljKDi1aRpj+zKsMT0QDAuZQ96xHgjHELccwiXS2JK8=
  - secure: p8GCpBwvk0B7A5L5AnlgkKnXSkQ11tdqhesofUon9E3l8DOuOmcWJjxXXeYYRPHKpzxu+MBJuotLmqaUWCr+h6j8thmn46hkHLoVRLyWwjmz1+O19o8WECY4U0b8kqi80d2Z2rIp3fsO/C+LSJa4SJw8wvCKV/Va+dvx+iYiom0=
  - secure: ZQGGb5Mco+/QVTuMU0X3mLd+t6cB0jvPTusgfKFhUisvM7Pi72dwTqamGt3KzZZNGGfZLmM0qM90UsThZvUpswS372ZLLlMCWZc9/Sc+Px6fcA3q5+rVinR2fkb/s9+VyiaMMdBV41XFh5OZA4nQxc4gpScPErw5/lONQt+FlLE=
  - secure: S28jd5sypO6f1uVWlNKYCKaiSNNSaI5fWTFnWUtw+IiTA+RMUlI/uL0qOLkb9nsPSYJjx7AyUSGVYp/7sAyKYzAT/Qd17FnrWCRGzcE3QDy8m8RwnM5MPgtrYG1kw9iA+Lz53SuDwzYKX1jcsFs2hSqXiC8EnL/rmjcS4fnVa/M=
  - secure: sFU0yaOOSgpOJeAMtWWBEUIbKSeXXASsymqFpOwiG83guTQWI71V0iQYWGziUh71iXc4UZ0rSHSo5LXaRGrSJM+wEC0E3lQdrKcnmReo+e2fP3eCkXkXWPLq+duEvmNBpPTt+4jNW9bMvieZxGKqBq0IgsGoVCDw/1Hkr8ioUl8=
  - secure: jUvRKJf4s3Emo68Oxqh9kkFNv8qwc0sBhfngTAtOKGcyJIHQatFkMGIOkDSUzScNkXJRDV3OltP3/elz0K+WYAUXy/PayogNKa43s4b60WcXTFoFt94IC9rgy8uysqg/tzm8QjgX9ZGPzbkuSS2QSqn5tQIq4n3pTihkQZ0nWfA=
  - secure: A2gbevDi5NdkQLQlXgIwbj2rY7R8EWNtCMRYCWRYP7YvHKcYSoMH9QGNs3+1byOsXpvz/voCJCOCDhlo9AzaCBSQsdmELeN4061/3AB2Sa3gVUvBhyt782fWELlj9dmAUbnevfSbsWZPDpXGf7QZbiGycMwDVl/Yv0O9e8gkc0k=
  - secure: MspxQfHhmcVC6Y36U8KSBNHQAP1sltocKMpv81DdCxHAaqtAIskTNdJyN8l5t6Bx1JDz8/tuLSvohs9gEVSI8yuBcgGaylY7xHd6m794pn/uGNGWgq0j60lNGRNZgDa+wbt+OhWIUuHlg+bHGFAS9bw2wsBNSbiyCjW4EDAa4Mg=
  - secure: ghVK3XY3PgoxENJtBdZzC7b+4c4N3C1LXnR93vQ0+WRbfsCOyy8SebP2jq1MSKtb3L5vWy1udJpOSaWn8xCJDc+MHQbkBB61KRN1HUd0rVu7ww5ZN1HIef3OwHUiKt9cTicFKNp/q2e59GfX4m9CCSlCIePaUvDWhVrIC4j2c/g=
  - secure: SmE7yDnHIcfOpo0rV/rvK+L4PFi4oSQV8J+vpots+7G612Uu02pOOxZyz9g3wmCXMlvZz9YLQdJaidrrr9opGym8nyn9BFWVWnr0PpfJDGccAd6p4k61mwF28+tUrfyatCSyuilAo8de7XeOcM8np/uced+tJEDvjwN9ZydI+Uo=
  - secure: HcxL6B/jMfv0PbE1XMvyz5M078a4UVv+rObX9NAkDqNFBgtMASybV1MvP30xr2CLvV3wkJBDrU7Go1K3crEdEcKcprWvFdePuQj9Iw7VjywfkamKP1GTKE7ySnDuAxSxsGKXyK6TGhgse57FOn3R0SMcvrAX0ixnp5XBSFVPowo=
  - secure: iFpl8uQlDUPHfOW03lNjg2zv5he3eOskozRCGHlrkAojsQqkGMOCKwOIHSDT3PQ7DsmNmmGOqBJwhCkUjSIT3szLojKs5FKy0YWqyut9AEAG9x+cZWJn4HYF+ADTcOY9iOANP6MsV4lWbNmvaimoO6i8Qw/R1NX6YRWD8x/qnh8=
  - secure: OX1hfjHiS8r/TNyF6B7CDS07rzuKaSxzQMl/oSGlesvuhovlLXQ7VTM/eYE8ugK7X9Ox5j1zDc2Xi8oA/9+gvaYmAIbU33eDJU4q3swjRM+p8YhoDzRPKV1180Ji/tApkf1//GPONObaw6rc/1DIcLoV7ZcLLfsppAuEXE1x0kM=
