sudo: required
services:
  - docker
language: c
cache: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath # needed on ubuntu 14.04.5 LTS / trusty
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage-deploy
  - chmod +x dommage dommage-deploy
  - export PATH=$PATH:$PWD/

script:
  - make configure build
  - dommage-deploy

env:
  matrix:
    - FLAGS="-t unix -vv --net socket"
    - FLAGS="-t unix -vv --net direct"
    - FLAGS="-t xen  -vv --net direct --dhcp false
        --ipv4 46.43.42.142/28 --ipv4-gateway 46.43.42.129"
      DEPLOY=1 XENIMG="tutorialopenmirageorg" MIRDIR="src"

  global:
  - OCAMLRUNPARAM=b
  - DOMMAGE_DEBUG=true
  - secure: C9crKCTsLIdSBi6YNVmt4J++UOxu3tNdUoxnawMLU7O3AtaP5zqCClKh5L5g9fyIxIcHBYPb0uYNEbh24zQegxJE17IQtgVWV8zdB0ixhFGk6SVVRhKdNdmvOjctLZcoXtp32TyI9CIyVW4EDCWf6ayfV0W7wLpbJRe9k5va6k4=
  - secure: QAcqtGMihH0CatcE2wA2b30wrBovF1EsnJco60EyzX7JR1cuAtWQ5T8GHs2ynscBdrSMxr/ewMv6RZ3Kb6NGxPBd5Gl0MVBkwNRCKf1ik4vDn2cuLMJN8XhDdS86670DJS57MG9n97MJU5/vuFSPxt+n8miaQmiQZw8KcwiQ0J8=
  - secure: Ye1tRnS3SfA96mmcE1Gh+N+SYYCQSyu0BbF167FoDKMCY92BfQgfxQH597t/8TCgzSh7Dg6+9g5aGrHr+3hUH4vIFCkmCdnjINh3GS6SAJdH0yTYPJ6OgGGMigBkiHvPhgSgyoEWkthPygK6RpF1uPebviaGlzavPtoMKwjaRrM=
  - secure: QFTohvw5Ff6HXNesaba2uR+qna4akGqypMfVYVHlJRH0IPsTIKVnkba6IJGG65IEngrTb51p57EAbBb7M4iu06vJmr5SSDGs+SQETUye+2eFxlAptgiFb+X3+fl/S3M4AWJpilnUoXLvOnj7VPguQ8QjMUvH6j4cMH6nHVHjYL8=
  - secure: WOZ8pcpJKHo/yPyL4dxTtj5x2/DY55B3OX3my6ifcmzuEf5W5runASQtZCWLLwdEF+n+XQqZR6slNP6Ai+SzFwIy6TC48HhC11unEIw/xf4JVA9WZOVj8pnW4TZCZl6sRvmSjibJjbDCsGBzov+Aa8VEaOfFl+EcsCvLLpCXnyM=
  - secure: emueR0OpR7J4/4LKyFbKH8zibg3FfrihiA8LLwJOFkfoG2kuIkftlvhW8Eb4LFMlk7ESswCndYGjB5zCLMInz9sjrEn8Q2zdQ7d4iuoLdlYnGD/uwLMZcGz/a6a+Vh2TE0uRTje3c1FIYvBFrPTUHGZrx06GDRJeP1pJ9X2v/qU=
  - secure: sOXHXEzXMvjgDFX/QeVsR3KnHjN+vDren+7uaC8b/Jiv3HOvGuUsh0NAgL1CkFyjdFsWHBg29AZihJehshqGNwFp+6S8faz3uXFiY0cCPztoy8bkyzqJmYapdrCNKiLA+Eq2Aat0OKj30pTw2waPDu3+Xb8WNFY0wjNilcfXSe0=
  - secure: rkEv9ZlCAGF3NGR2iyWdLFTvYml5YgmLVuoaiGm9hEL4+/85rlBfR0f8ZTtRQ526CYC6WCI0/f5rOzwlZxBGsWsFvaEzrXbLuC8DyUQF2wguak1hYU8oek5BWQ9JBiyCnK9DFOvgkT90yPZf64kVbkjmdbiGZ0Z+iaGXfC8MgZQ=
  - secure: NGFUdyPeDKS+ECfX8d4lLSngJv0tw6RinCsf1/1j+3qwAQjkgZCd3hK789TmSiF3hY0OACSVx2zp00zxJM+L4uWDWJ7qRICCald0Y8pxgrqPlbExfHHFqnMZWjfMtZclyttbl/QQ9zxaNI6e5wa2byeDH3YuQT75kNFDMOqNFIw=
  - secure: ZRSmPowrIrXVpm/6dSm5i1JABDepwv1gLI4Gu0V+VAZ9Z0kDY4CM2dj0HcwyfcT+O0GmayicDyj3QrK9l6P/urhzEBVqXeWyyCogVdaZavDxIN82k8f/lBrH2vDifAqgcmcsMadyjNzbkME6AiUQBodQm5LJMrX02vYZKuzQJSo=
  - secure: LgGvmM6BFmvpchAmX8Y/uMrzcD+h5vp31t2D1QLhabO65siZqRLFux1vRUJKSJoz5X8P7qB+0rSbAhQRQY3s7LxBaqwoAE0PWIeMOvveMa8xxLPjUWIDrF3HKHJMhx8VB+NUu4Gx7FRYDTs6bf3rMsyzl4wBw0cmChd6imQHRmk=
  - secure: K01NAA2htuRAx9Y8wRPH14ffmrLX2pQcHFW0WfbqluyEwzQ/fOvZ1kJCpvvGf6h++dnWJf+VqYe5GrU3WCJqSQyQILdjKlBg1D17FzoUYsCXbk1pbDP3zVR9FWbLl6zDBpiWwNRANr3EBD22hu7ZT3rRfqe/r41u1QmW0JHYn8A=
  - secure: NLHEL0S2W6uLytkRPxooywGVqtT7uT0CuBlwNbz+OdNJIA/NscP3XQdXOyq+oZ1DV3J9IibDRDxkd72TWVSHWVXxfFITpOg2LUu7yb0gQKfG5xf1Up9PhzJtsGerdS8IKDzXUwB8dVKI9QnwyOqk6JghLKiuiLKw4ZgG446pUOA=
