sudo: required
services:
  - docker
language: c
cache: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath # needed on ubuntu 14.04.5 LTS / trusty
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage-deploy
  - chmod +x dommage dommage-deploy
  - export PATH=$PATH:$PWD/

script:
  - make configure build
  - dommage-deploy

env:
  matrix:
    - FLAGS="-t unix -vv --net socket"
    - FLAGS="-t unix -vv --net direct"
    - FLAGS="-t xen  -vv --net direct --dhcp false
        --ipv4 46.43.42.142/28 --ipv4-gateway 46.43.42.129"
      DEPLOY=1 XENIMG="tutorialopenmirageorg" MIRDIR="src"

  global:
  - OCAMLRUNPARAM=b
  - DOMMAGE_DEBUG=true
  - secure: C9crKCTsLIdSBi6YNVmt4J++UOxu3tNdUoxnawMLU7O3AtaP5zqCClKh5L5g9fyIxIcHBYPb0uYNEbh24zQegxJE17IQtgVWV8zdB0ixhFGk6SVVRhKdNdmvOjctLZcoXtp32TyI9CIyVW4EDCWf6ayfV0W7wLpbJRe9k5va6k4=
  - secure: QAcqtGMihH0CatcE2wA2b30wrBovF1EsnJco60EyzX7JR1cuAtWQ5T8GHs2ynscBdrSMxr/ewMv6RZ3Kb6NGxPBd5Gl0MVBkwNRCKf1ik4vDn2cuLMJN8XhDdS86670DJS57MG9n97MJU5/vuFSPxt+n8miaQmiQZw8KcwiQ0J8=
  - secure: Ye1tRnS3SfA96mmcE1Gh+N+SYYCQSyu0BbF167FoDKMCY92BfQgfxQH597t/8TCgzSh7Dg6+9g5aGrHr+3hUH4vIFCkmCdnjINh3GS6SAJdH0yTYPJ6OgGGMigBkiHvPhgSgyoEWkthPygK6RpF1uPebviaGlzavPtoMKwjaRrM=
  - secure: QFTohvw5Ff6HXNesaba2uR+qna4akGqypMfVYVHlJRH0IPsTIKVnkba6IJGG65IEngrTb51p57EAbBb7M4iu06vJmr5SSDGs+SQETUye+2eFxlAptgiFb+X3+fl/S3M4AWJpilnUoXLvOnj7VPguQ8QjMUvH6j4cMH6nHVHjYL8=
  - secure: WOZ8pcpJKHo/yPyL4dxTtj5x2/DY55B3OX3my6ifcmzuEf5W5runASQtZCWLLwdEF+n+XQqZR6slNP6Ai+SzFwIy6TC48HhC11unEIw/xf4JVA9WZOVj8pnW4TZCZl6sRvmSjibJjbDCsGBzov+Aa8VEaOfFl+EcsCvLLpCXnyM=
  - secure: emueR0OpR7J4/4LKyFbKH8zibg3FfrihiA8LLwJOFkfoG2kuIkftlvhW8Eb4LFMlk7ESswCndYGjB5zCLMInz9sjrEn8Q2zdQ7d4iuoLdlYnGD/uwLMZcGz/a6a+Vh2TE0uRTje3c1FIYvBFrPTUHGZrx06GDRJeP1pJ9X2v/qU=
  - secure: sOXHXEzXMvjgDFX/QeVsR3KnHjN+vDren+7uaC8b/Jiv3HOvGuUsh0NAgL1CkFyjdFsWHBg29AZihJehshqGNwFp+6S8faz3uXFiY0cCPztoy8bkyzqJmYapdrCNKiLA+Eq2Aat0OKj30pTw2waPDu3+Xb8WNFY0wjNilcfXSe0=
  - secure: rkEv9ZlCAGF3NGR2iyWdLFTvYml5YgmLVuoaiGm9hEL4+/85rlBfR0f8ZTtRQ526CYC6WCI0/f5rOzwlZxBGsWsFvaEzrXbLuC8DyUQF2wguak1hYU8oek5BWQ9JBiyCnK9DFOvgkT90yPZf64kVbkjmdbiGZ0Z+iaGXfC8MgZQ=
  - secure: NGFUdyPeDKS+ECfX8d4lLSngJv0tw6RinCsf1/1j+3qwAQjkgZCd3hK789TmSiF3hY0OACSVx2zp00zxJM+L4uWDWJ7qRICCald0Y8pxgrqPlbExfHHFqnMZWjfMtZclyttbl/QQ9zxaNI6e5wa2byeDH3YuQT75kNFDMOqNFIw=
  - secure: ZRSmPowrIrXVpm/6dSm5i1JABDepwv1gLI4Gu0V+VAZ9Z0kDY4CM2dj0HcwyfcT+O0GmayicDyj3QrK9l6P/urhzEBVqXeWyyCogVdaZavDxIN82k8f/lBrH2vDifAqgcmcsMadyjNzbkME6AiUQBodQm5LJMrX02vYZKuzQJSo=
  - secure: LgGvmM6BFmvpchAmX8Y/uMrzcD+h5vp31t2D1QLhabO65siZqRLFux1vRUJKSJoz5X8P7qB+0rSbAhQRQY3s7LxBaqwoAE0PWIeMOvveMa8xxLPjUWIDrF3HKHJMhx8VB+NUu4Gx7FRYDTs6bf3rMsyzl4wBw0cmChd6imQHRmk=
  - secure: K01NAA2htuRAx9Y8wRPH14ffmrLX2pQcHFW0WfbqluyEwzQ/fOvZ1kJCpvvGf6h++dnWJf+VqYe5GrU3WCJqSQyQILdjKlBg1D17FzoUYsCXbk1pbDP3zVR9FWbLl6zDBpiWwNRANr3EBD22hu7ZT3rRfqe/r41u1QmW0JHYn8A=
  - secure: NLHEL0S2W6uLytkRPxooywGVqtT7uT0CuBlwNbz+OdNJIA/NscP3XQdXOyq+oZ1DV3J9IibDRDxkd72TWVSHWVXxfFITpOg2LUu7yb0gQKfG5xf1Up9PhzJtsGerdS8IKDzXUwB8dVKI9QnwyOqk6JghLKiuiLKw4ZgG446pUOA=
  - secure: G7Rk+veseQUu6JvpMkg1wK+QMTgLZUKEohmNG5pp+HDfZx1xLtcN7G9ka8EfxdUacBFOS+YyQoGrtjPgPDJS2FJradHXGiOLZ+f0zjEWrwnaEAgGhpGfF0jzgGAR1RkJVzjmad/v8zcr4CJtAEwBcVPvZIgn3GIykAyBmITpan0=
  - secure: UZ1xjhD+zeYMnh+R+PTJpy4Zg56VZfsHoJL1VlHyEiItlQHwfNnfz8zgx/1W6mhAV3Hmmz9zLXWzbWdIOrq/SzXOk44Tm58zjmx4YASjOEi5QRNo/GxJwiF+LaQ1/64l7dUn1Wb3cDZVGDnDOe+yboI7/aVcfy6vCBHvG9VtSBM=
  - secure: d0nXAMT3STGqcYINAhoDjVcgk4mCIa4c04I1U/R8yw6tH9UFfaxS0sbVwL4CSc4KGsnr1JQk1Ap1cUh98KRP4gQQqkgNiypzEfLRjsO86QdXFD5sYe7wqM2e+lWJ6ClK7ZSh9jPGVbZD9nE5jxU9zTxjXxJxE50lF9Ffppx9RqE=
  - secure: hmketlUckd5Ez7EGFkvrjPd7/PW3ZisOpLDzjdWpoSSIzE/URNPSkpLslPwTj4LIc6OljULuDWZ+7qvwMMnFLnj1oXqsfZ+AZIcwHfXhwFDKNBEebx6QXv2syuhTFD0EcOusZ45k5JvfZIlbSCwKXAr2YpBcXsGcY+XuGBWMbs0=
  - secure: XHfBjqT5RUSrPsQ/l/Fdo0fjdb0EhdtMCHJ3oLQ4c+D2g6g8DjdRJrlVxu1ucyRb6sLhqatCm0drkHLxcMPxjTeXPmqZVTKgkSVC2MBFgc1Kz5BNq5i+EGwQ5Skhu88msllVojHXasfQY9ej2ldOXL/zw1zE5rlOwHOicY+SpgA=
  - secure: iyr3Zi90OGpmkeEkUaaGlJYGlwDAA+HAfXsTreWoRSDqkktX/pDziE5NzcDXSAOdAu60Di0UhT2n0ulMiz9LwG3Z5WRo92fsdHe66mzTK/LBhGHwAnF0fCroOjjmRN6IWg83PvqE0vni6PwBOuTcsMJM8hyNe8SLufH76eANEh8=
  - secure: mNg38klyVXpcCVfrD8DB3bpp8hMIqRgI97FrdCDMA8uUTaeeRXiqTvOVnYjjWasFvqcNW4RYf6miGCzxsdiZ0AZYOvlmdPzUp1PvuhO14WNrT6XMhPWO3oP857IohXHH52EnxWRUbjC8iK9/xu5DiNfTGz7kJiewnP7JVwjosOM=
  - secure: oQmGxHiaOvqTqQmaXn8sR7Rw4EM8gXIn4vtn49zC/K0HGufcq6gtfbCKG2BSyjqeUnN+lmRuGpvPyFUzmPr4MYZgcfQvoeAgfCMWrNgeUwKqgcBTetYQfYqGr1KjAdd/vUg/5HGLKchpBqRmcLM5sxQtgfdLIK1hPMKoFsXj80w=
  - secure: f/jbVxcg4q9lfeUXeKxClwNRSAPxWgQLYh7BUWV1qpik0GJyKwdLbq4xsEPbocH7FpF3E6mCEBuNoa0AmI86JubxasQJH3QkfpVZfHh85cBrchL+41zaHsA3Ihv1ecH6S4iURje71fTuy/sJXddfkj2bxdzMKiLHxks2zZhgEdg=
  - secure: S5RpMX1Bw+tIubOZut6OqmHOjc0xN7+juh55RKBvJPx6zYLMV/DNxoI68mlBcX3xMdooByCJXSVcOepZQ+kVX/YMvTDXCI/D6at3McqXc3PtpcuSD6WJNxNIP5BHVdIAnDLggQhCDUHF1+Z6UtBpWeJSl+JJ9ze2iS+CzXzCJIE=
  - secure: Ei6/X1rqhTx+EUx3YBeHwV49ovxc8Xc5tSMiy+GlfR2GKFz1rNO5I/RhktKZBQYMbjQUsBW+QCTxCJeB+yj/AydnP1GVuJTOkmYEbKWqDM2XudsPiaNlkyn0t+p0R8JN9EyAFcH0qAd6u3yM6HbHtyXeCwqnQJOc7ssR0ztDv4s=
  - secure: PRovKu3dZ+SIOBb9qczK9HlFECfjnAfnclUP8PSX3qYoePSNwKyQzkS24BcOt5g67grc+2OFC042wAGlLbsqNkG4hUVTCLZ0+6/k/gkUeQAVt0WeEltVXW9a2+nqJiY1/PWDP0cL934z9Ue2OoBMyYc+G1ragOucYm6ObOUm1i4=
  - secure: eL2kTzwgNDf81yb+45cyysjs/URibXVvUNx6D+i3dpkdouyIJlg9YyCgFOaaSvfHZeBvRDrppjDenf+akk+jMnqyoUQiJdP/euz4ZlWUVZmwrYs3clccb5baXmGhXK2RjWmR3OaA4BCEscsh9M62bzWiGU30dvVzHFt9z7OZudI=
  - secure: iOZ1RDmNB8RO54icCGo/vwZViO7AdYWF/nPDFCrnPtI2GG4O78inNWYCX8/v8L7kyj3XTwnafYPDFPFkMnPpeCHPJVzKNgI8WTIvCNxggxF3OWxm5kHDq/oZ/1VxSOJEpmwbI2mssXhEs6IR57zFXfVDhx+Ujg/EmYv/P18l1tc=
  - secure: phsJRgGehXnBz7OMVwxq048QHKuHE/vHbu7/3vGjeXA4uyo++sTDsQdb1ONJN0BjnuyXzMHHU1GJiU152YMj9pycidk9uIcfPtcEBXRiqBOkuhzswQs5ZXApoIYTrY0MQGLv50aXwNxIIVSyUKSMaC9mc0F5XbIE2kqcBBTQsSw=
  - secure: joEtYpaaXdX/601nF1D2oXStFNl1Pd/Q5kW4RUK/8M1fNZtdN7Q1Nsb6kvy0hpPd3Gxp7co6X/vNDEZmgOnhlGCE239AGYP1yGhwv34lJPQAYX/VWDncbMKu24dXu9QcZGrF3kBN4q0uHA8iGfmF8QeoVZnCtNkXpNoQBdlHciM=
  - secure: hHAxGvvpczPRdfBKt12YjKhKydO98aAsGAFmiUkztQSo5wyk7DJE1egp6fKYCZVjQsXAKbc0Ssae9LmWUlNtLEms6qyXFbYB0tC0SaZ+danijfKXKaSmI7Oooc3/2BncIl2nX0aiRlHOXX8vKKsGxN66wFuYKtztGgynoYX2SQI=
  - secure: nIdxrAYFwC/TR8zK17cICLaeH9LQfRenI9Z6bxqbR7nOfpVcmpyDud4eObKIlWiwOCBpiFpyCATUkpgAb9skbASDttGiaj4HqtyRJbEqshZVaF5f8MHc+abadNUuCMqdVnmCHANju9KrisMNT54PGknXf3PD1xxmRWKXaKhXZbA=
  - secure: PHqSFQqOH1Y7n/b3583lTk0yJr/KKtTmW3z33UWFu+95DqYZsb/8sN/w4nGfMFKJwHVaiWf+UfpeM2HBXzFoVO145CFjyuBMSycPxcyJvk6n4+DZLEF/32JMJIDmZatY8ZA+yTCEm5sfnmHywRd7HMg8pdwTVYRjsl7697vBGV8=
  - secure: DHRGUvnMB1Ny8SoGvesAbA07etIW6ik0EvvMW3b9S4GAnIfmfjijR9g+pCedbb6r1AcDAkoDeoLBYZgYpZZiCfEFaodu+oSvSiJAMbFlwXtd6Y5AqQTTC7Fd1fmDrEhV4kwdpUIc6g83qYFB9vKvCeE1e7tduM+OHzpWeP0U/n8=
  - secure: qvrppeneoUpIYT0t9B/wQafp170WoYbKKQNIuAs8qMiGIl+qfXY/aATtmA8G1ZeSoD8ZcsCZPSzvvK/ugI3+qEgD5M6jIgKBM4C/9dtZclmDa7InqgU/hpHHhLSczL2kbX0ZUTUv8G3Q2X9XVIFoEX/S76w416khP+Is6Rl+qqU=
  - secure: AbrbTHNkDwyg33LdzHJMQZ0pUYULuT48ddE9UpVSQDgim5/npjE0DxhmdvaTo1ermy8xSx7T4HjLgzMMBcAfYnXN8MC+YhpotEJV7PmFW4rC0tt3t8yKkNdwnt0dpoJMeJo2Oh/rYp/jXlD1yHWqniLziR+73ttFPdCps5R5dg4=
  - secure: L8+/LvUJGtSbnT2PZwdv+r6eISDge7hKetVhItEPRzR026sl/Xc4qVfQ6VbPbZAALnWln8UCxBzN5gZbp9aGYyMVRhZdRVuZw1B7YLoo4SlyG5Z+DaHH/BtY/yogaV+Up5oI3vQPgWwhBkrrhe5rUf/tytr/sZyawAjZNYAbEKw=
  - secure: P42mQ99PFwYK3hk3ywZqsY9sqbssC5QbGno8giOtRK2fY4g2QtfDsl9QZdGfJ4flWaTg8wSsZ1Sq2ULOitYUX7BTRXDvWCCUjUKmJVPDshfuK/XRu0B2AWD3aPOGCMqbXU0vzC/GAt9ILTWPEBzd6JmKQsIzXeCc1r6maFNa0SU=
  - secure: KPl0kfOX6f3QnvTpeb5/e8uDe4Ltg0psut0bnE5cwgajOP/XW9q5xnxyOrjOxM/RSZoZavKRf5vy0tkDPXy35JdeWyEDPYR8L2WI6gfvXUCVqbtJdIynpjohQ7hMgg9bIgfGqCAogxWnu7s7T7PePVhQoMZA6YQfiYEBmrR3ibU=
  - secure: XR/pR00nHBaYLlw7vvUvHk9f/YFDz998727dHRl2zJ5NBJ6e8uSFxN4aZjKtAY/QuggKu4MoPMFgKaD7oovSx9BOLB9sLhx3GvAtknUpxmh9+aFksU3BuA8mMOSVhEbHU34qmZa/AS2SVSUfPoTejayV1zclz/ArDRbsO3nBEeU=
  - secure: mHgLh64PZ+0AQbyb9+GBp6TZcRaKaiXouYnBayk3oNE1616+r8PNKhJYCHRlUINexFbfEpzEcwM1vVqTFCNsPh/bA2p2UQ3L6TkhPq8b30yvLdiF+s2ewCP5ba6/PSMeEpmFWGiqtzEYBwgL0lKSn7cPbPWz9EAXrPjtPyXZBJ0=
  - secure: Jt7o03LYsuHh2wIR5Emvq257nQxQ2VO6LBmYAuyQhQXp/tdDIpOlrNZY83TyCQKJlLpy749G/Vv+GodYObi3x1UtYRyOwdEp7oIqoMO77JlxsnIw+VuT9yXtHbQVXa0IC+K7pnK38QloAUgQlLIz3SpD6QPk8XHHa2B684emKKM=
  - secure: lI9sqxIz+k9gwn+ZXf+1PZHwDkK3kZh1s0lYa8tH494K4G2eV4Df3t49ecuhtmL7agG09fOgJKf9GF2uybtg9PEcuW1UtuvB6xL0UdWjo8EUMm2CjbuXfSFLtTpKeDKQCH8hSi8YOJz4IQUuVYk02bI6ZgC2CjO9yj+jf4olpiY=
  - secure: JtP0pUk0MiUuwy7IwdgsulTkwKIdA8EoHHwAHyuM9kCDt6xJE5qi4N66nOuAcSTLhmrqKhk6VYzH2FZEQfIUAzbXGsvLVJ2NfJ1MDwcQH5K8eapopOFzALDd6Mn/wfN2aPIyqgXbkMkEKWQThP6hnk9Lw1fxzyWUVyoxt4NeKDQ=
